runtime: python38
env: standard
entrypoint: gunicorn -b :$PORT app:app
instance_class: B4
service: chessbackend



runtime_config:
  python_version: 3

basic_scaling:
  max_instances: 1
  idle_timeout: 30m

env_variables:
